config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  namespace :admin do
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end

    resources :products do
      member do
        patch :move_up
        patch :move_down
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end

    collection do
      get :search
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  acts_as_list

  self.per_page = 20

  has_many :photos
  accepts_nested_attributes_for :photos
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"

  def new
    @product = Product.new
    @photo = @product.photos.build #for multi-pics
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      if params[:photos] != nil
        params[:photos]['avatar'].each do |a|
          @photo = @product.photos.create(:avatar => a)
        end
      end
      redirect_to products_path,notice:"创建成功！"
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if params[:photos] != nil
      @product.photos.destroy_all #need to destroy old pics first

      params[:photos]['avatar'].each do |a|
        @picture = @product.photos.create(:avatar => a)
      end

      @product.update(product_params)
      redirect_to admin_products_path, notice: "成功修改商品信息"

    elsif @product.update(product_params)
      redirect_to admin_products_path, notice: "成功修改商品信息!!!"
    else
      render :edit
    end
  end

  def index
    @products = Product.all.order("position ASC")
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path, alert: "商品已删除"
  end

  def move_up
    @product = Product.find(params[:id])
    @product.move_higher
    redirect_to :back
  end

  def move_down
    @product = Product.find(params[:id])
    @product.move_lower
    redirect_to :back
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
    @products = Product.all.order("position ASC").paginate(:page => params[:page])
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "成功加入购物车"
    else
      flash[:warning] = "您的购物车内已有此物品"
    end
    redirect_to :back
  end

  def search
    if @query_string.present?
      search_result = Product.ransack(@search_criteria).result(:distinct => true)
      @products = search_result.paginate(:page => params[:page], :per_page => 10 )
    end
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end

  def search_criteria(query_string)
    { title_cont: @query_string }
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
    excerpt_cont = excerpt(product.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title, label: "名称" %>
  </div>

  <div class="group">
    <%= f.input :description, label: "描述"%>
  </div>

  <div class="group">
    <%= f.input :quantity, label: "数量" %>
  </div>

  <div class="group">
    <%= f.input :price, label: "价格" %>
  </div>

  <div class="group">
    <%= f.input :image, as: :file %>
    <%= f.label :avatar %></br>
    <%= f.file_field :avatar, :multiple => true, name: "photos[avatar][]" %>
  </div>

  <%= f.submit "提交", data: { disable_with: "提交中..." } %>

<% end %>

<script type="text/javascript">
  autosize($('#product_description'));
</script>

app/views/admin/products/edit.html.erb
<h2> 编辑商品 </h2>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<h2> 商品清单 </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th>quantity</th>
      <th width="250"> Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.photos.present? %>
              <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/100x100&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= product.quantity %>
        </td>
        <td>
          <%= link_to("编辑", edit_admin_product_path(product), class: "btn btn-sm btn-success") %>
          |
          <%= link_to("删除", admin_product_path(product), method: :delete, class: "btn btn-sm btn-danger") %>
          |
          <%= link_to("向上", move_up_admin_product_path(product), method: :patch, class: "btn btn-sm btn-info") %>
          |
          <%= link_to("向下", move_down_admin_product_path(product), method: :patch, class: "btn btn-sm btn-info") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2> 新增商品 </h2>

<%= render 'form' %>